apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-worker
  namespace: {{ .Release.Namespace }}
spec:
  serviceName: {{ .Release.Name }}-worker-headless
  replicas: {{ .Values.replicaCount }}
  updateStrategy:
    {{- toYaml .Values.updateStrategy | nindent 4 }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: APPTASK
              value: "worker"
            - name: APPNAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: APPMASTERIP
              value: {{ .Release.Name }}.{{ .Release.Namespace }}